#Enabling the repos
- name: Enable Repos | Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled

- name: Enable Repos | Enable required RHSM repositories
  rhsm_repository:
    name: "{{ rhsm_required_repos }}"
    state: enabled
