#Enabling the repos
- name: Enable Repos | Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled

- name: Enable a RHSM repository
  rhsm_repository:
    name: 
      - rhel-{{ ansible_distribution_major_version }}-server-rpms
      - rhel-{{ ansible_distribution_major_version }}-server-satellite-{{ satellite_version }}-rpms
      - rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms
      - rhel-{{ ansible_distribution_major_version }}-server-satellite-maintenance-6-rpms
      - rhel-{{ ansible_distribution_major_version }}-server-ansible-2.8-rpms
    state: enabled
