- name: enabling repos | checking pulp directory is owned by apache  # FIXME: why?
  file:
    path: /var/lib/pulp
    owner: apache
    group: apache
    mode: '0755'

- name: enable repos | RHEL repositories with label that need releasever
  theforeman.foreman.repository_set:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_server_url }}"
    organization: "{{ satellite_organization }}"
    label: "{{ item.label }}"
    repositories: "{{ item.repos }}"
    state: enabled
  with_items:
    - "{{ satellite_rhel7_product }}"
