- name: config domains | create or update domains
  theforeman.foreman.domain:
    username: "{{ satellite_admin_username }}"
    password: "{{ satellite_admin_password }}"
    server_url: "{{ satellite_server_url }}"
    name: "{{ item.name }}"
    description: "{{ item.description | default(omit) }}"
    locations: "{{ item.locations }}"
    organizations: "{{ item.organizations }}"
    dns_proxy: "{{ item.dns_proxy | default(omit) }}"
    state: "{{ satellite_state }}"
  with_items: "{{ satellite_domains }}"
