# tasks file for yumupdate
# TASKS
- name: yum-clean-metadata
  command: yum clean all  # noqa: 301
  args:
    warn: false

- name: Remove unneeded packages
  package:
    name: "{{ satellite_remove_pkgs }}"
    state: absent

- name: installing secuity Packages
  package:
    name: "{{ satellite_add_pkgs }}"
    state: present

- name: Check if update is required
  shell: yum -q check-update > /dev/null  # noqa: 301 303
  register: patch_lvl
  failed_when: patch_lvl.rc not in [100,0]
  args:
    warn: false

- name:
  block:
    - name: Yum update the system
      package:
        name: "*"
        state: latest  # noqa: 403

    - name: Reboot on new kernel
      reboot:

  when: patch_lvl.rc == 100

- name: Refreshing Ansible facts
  setup:
