- name: install | get package facts
  package_facts:
    manager: auto

- name: install | install satellite package
  package:
    name: "{{ satellite_packages }}"
    state: present
  when: "'satellite' not in ansible_facts.packages"

- name: install | remove installer script and tuning yaml if forced install is wanted
  file:
    path: "{{ item }}"
    state: absent
  when: satellite_force_install|bool
  loop:
  - /root/satellite_install.sh
  #- /etc/foreman-installer/custom-hiera.yaml  # TODO not enough, old version must be restored

# copy template file with scenario options and only run installer if changed
- name: install | copy installer script
  template:
    src: satellite_install.sh.j2
    dest: /root/satellite_install.sh
    owner: root
    group: root
    mode: 0640
  notify: run_installer

- meta: flush_handlers

- name: install | move performance tuning yaml to
    /etc/foreman-installer/custom-hiera.yaml
  copy:
    src: files/custom-hiera.yaml
    dest: /etc/foreman-installer/custom-hiera.yaml
    owner: root
    group: root
  notify: activate_pref_tuning
  when: false  # FIXME file is rejected by Satellite 6.8 because tuning option is no longer valid in PostgreSQL 9.5+

- meta: flush_handlers

#- name: install | run foreman-rake to import scap content
#  shell: >-
#    foreman-rake foreman_openscap:bulk_upload:default  # noqa 305
#  register: openscap_rake
#  changed_when: ("Saved" in openscap_rake.stdout)
